### ISSUE TITLE
goblin module name resolution error

### ISSUE THREAD

**Issue by barelyhuman** [BetaPictoris/timeleft#2]
Hey, 
I have a tiny little service that allows you to install go binary apps using a curl script

There's a tiny issue though, the resolution path of the module is `github.com/BetaPictoris/timeleft` and the name of the module in the `go.mod` is `betapictoris/timeleft` , the mismatch stops go lang from compiling the module on the fly.

if you sync the them to be `github.com/BetaPictoris/timeleft` , it would help with the compilation and the package could be then installed with the following

```sh 
curl -sf https://goblin.reaper.im/github.com/BetaPictoris/timeleft | sh
```

**Comment by BetaPictoris** [comment]
I've added the script to the readme in a2eb88b7eb63461986d449fb9fb1efc1165aac38. Thank you!
